name: CI

on: [push]

jobs:
  unit_tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x
      - name: Build and run tests
        if: success()
        working-directory: backend/ruby
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec ./spec